<?php $medicine = ['Acetaminophen',
'Adderall',
'Alprazolam',
'Amitriptyline',
'Amlodipine',
'Amoxicillin',
'Ativan',
'Atorvastatin',
'Azithromycin',
'Ciprofloxacin',
'Citalopram',
'Clindamycin',
'Clonazepam',
'Codeine',
'Cyclobenzaprine',
'Cymbalta',
'Doxycycline',
'Gabapentin',
'Hydrochlorothiazide',
'Ibuprofen',
'Lexapro',
'Lisinopril',
'Loratadine',
'Lorazepam',
'Losartan',
'Lyrica',
'Meloxicam',
'Metformin',
'Metoprolol',
'Naproxen',
'Omeprazole',
'Oxycodone',
'Pantoprazole',
'Prednisone',
'Tramadol',
'Trazodone',
'Viagra',
'Wellbutrin',
'Xanax',
'Zoloft']; 

$med_procedures = [
'Biopsy',
'Stereotactic surgery',
'Radiosurgery',
'Endoscopic surgery',
'Lithotomy',
'Image-guided surgery',
'Facial rejuvenation',
'Neovaginoplasty',
'Vaginoplasty',
'Ablation',
'Amputation',
'Cardiopulmonary resuscitation (CPR)',
'Cryosurgery',
'General surgery',
'Hand surgery',
'Laminectomy',
'Hemilaminectomy',
'Laparoscopic surgery',
'Lithotriptor',
'Lobotomy',
'Knee cartilage replacement therapy',
'Xenotransplantation'
];

?>

<iframe width="1500" height="690" autoPlay src="https://www.youtube.com/embed/E1IOO5wdPJk?autoplay=1&cc_load_policy=1?autoreplay=1" frameborder="0" allowfullscreen></iframe>